# Generated by Django 4.2.30 on 2026-10-02 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job_applications", "0001_initial"),
        ("job_listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="job_listings.job",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status"], name="job_applica_status_aea822_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["applied_at"], name="job_applica_applied_6af76b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["job", "status"], name="job_applica_job_id_c097ea_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("job", "applicant")},
        ),
    ]
