# Generated by Django 4.2.30 on 2026-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10 employees"),
                            ("11-50", "11-50 employees"),
                            ("51-200", "51-200 employees"),
                            ("201-500", "201-500 employees"),
                            ("501-1000", "501-1000 employees"),
                            ("1000+", "1000+ employees"),
                        ],
                        max_length=20,
                    ),
                ),
                ("headquarters", models.CharField(blank=True, max_length=100)),
                (
                    "specialties",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated specialties (e.g., Software Development, AI, Cloud Computing)",
                    ),
                ),
                (
                    "culture_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of company culture and values",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Verified companies have been authenticated",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
