# Generated by Django 4.2.30 on 2026-10-02 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_accounts", "0001_initial"),
        ("company_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="employer_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="user_accounts.employerprofile",
            ),
        ),
    ]
