# Generated by Django 4.2.30 on 2026-10-02 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_accounts", "0001_initial"),
        ("job_listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="user_accounts.employerprofile",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="job_listings.skill"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["slug"], name="job_listing_slug_c0ad3e_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status"], name="job_listing_status_108a0d_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["created_at"], name="job_listing_created_0be473_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["location"], name="job_listing_locatio_cb6452_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["employment_type"], name="job_listing_employm_bd22db_idx"
            ),
        ),
    ]
